### PR TITLE
Update the README since binaries are not in 'transit_model' anymore

### PR DESCRIPTION
**Pull request by woshilapin**

### CODE REVIEW

**Comment by woshilapin** [comment]
Then I can just remove the entire section if you prefer. The first goal of this PR was to remove outdated documentation. Instead of removing the section, I updated it with some up-to-date documentation.

**Comment by woshilapin** [comment]
> yes you can remove. we have to write a better README

I remove the entire section.

**Comment by datanel** [comment]
@woshilapin can you rebase please? we want to test the new mergufy configuration

**Comment by woshilapin** [comment]
> @woshilapin can you rebase please? we want to test the new mergufy configuration

I just rebased. @ArnaudOggy @datanel You're gonna need to approve again.

**Pull request merged**
