### PR TITLE
Made reqwest optional

### PR DESCRIPTION
**Pull request by datanel**

### CODE REVIEW

**Comment by antoine-de** [comment]
that's also good for me, but honestly #342 is enough for our use case if you don't want the burden of a feature.

thanks for all this work!

**Comment by woshilapin** [comment]
I'd be ok with only #342. I agree this would be a nice way to add it back but I really don't think it's necessary. I'm actually thinking that even supporting both ZIP and a folder is already a nice to have. Our API could be much more restrictive and accept only ZIP or only folders (which would result in the dump of either `walk_dir` or `zip` dependencies).

**Comment by datanel** [comment]
+1 for simplicity
-1 for responsability (but finally I don't care if it's optional, it's a good feature)

**Comment by datanel** [comment]
i close this PR until someone really needs it.

**Pull request closed without merging**
