### PR TITLE
handle route comments on line when using read_as_line

### PR DESCRIPTION
**Pull request by Tristramg**
cf. ND-1075 and replaces #736

### CODE REVIEW

**Review by woshilapin — COMMENTED** [review]
I'm a bit annoyed that `generate_route_comment()` might return a `Comment` either with an identifier prefixed with `route:` or `line:`. Then only after in `read_routes()`, the code is branching on `read_as_line` and decide to use this comment in a line or in a route. So in terms of code architecture, it's possible to add a comment `route:` in a `line` which would be wrong. I know both actions are conditioned to `read_as_line` so it won't happen at the moment but since the logic is in 2 different places, future maintenance of the code might break this invariant. I'm wondering how the code could be refactored to better reflect this.

I'm not sure if I'm very clear about what I'm trying to explain, so do not hesitate to ping me in private to better explain.

**Comment by Tristramg** [comment]
I think I understand what annoys you, but I’m not sure how to adress it.

First, we can rename it `comment_from_gtfs_route` to avoid some abiguity.
Secondly, would you prefer to duplicate the call?

**Comment by woshilapin** [comment]
> I think I understand what annoys you, but I’m not sure how to adress it.
> 
> First, we can rename it `comment_from_gtfs_route` to avoid some abiguity.
> Secondly, would you prefer to duplicate the call?

I propose [this PR](https://github.com/CanalTP/transit_model/pull/742) that might address the problem. Tell me what you think about it.

**Review by woshilapin — APPROVED** [review]
Good for me. Do not hesitate to squash/rebase if needed.

**Comment by Tristramg** [comment]
I just squashed you changes. Thank you!

**Review by woshilapin — APPROVED** [review]

**Pull request merged**
