### PR TITLE
Add SPDX license identifier

### PR DESCRIPTION
**Pull request by woshilapin**
In relation with https://spdx.org/, this is a proposition.

### CODE REVIEW

**Comment by woshilapin** [comment]
Waiting for some resolution on the problems mentioned in https://github.com/CanalTP/transit_model/pull/437/

**Comment by pascal-vs** [comment]
Why do you keep the following text:

```
// This program is free software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see
// <http://www.gnu.org/licenses/>.
```
in each file?

**Comment by woshilapin** [comment]
> Why do you keep the following text:
> 
> ```
> // ...
> ```
> 
> in each file?

This SPDX tag is mostly a structured tag that might be used by tools to give a status of the project. It doesn't prevent to have the header's license. But I realize we might never use such tools...

**Comment by woshilapin** [comment]
It has been decided this modification is not really useful, neither will be used afterwards so I'm closing this PR.

**Pull request closed without merging**
