### PR TITLE
[tech] Add code coverage in the build

### PR DESCRIPTION
**Pull request by woshilapin**

### CODE REVIEW

**Comment by woshilapin** [comment]
I completely rewrote the code coverage publishing:
- used `cargo-tarpaulin` instead of `grcov`
- used CodeCov instead of Coveralls

**Comment by woshilapin** [comment]
I updated the PR with a flat-styl-ish badge and removed the `do_not_merge` tag (I didn't realize it was still here).

**Comment by woshilapin** [comment]
Hmm, that's annoying. So `tarpaulin` is failing with a segfault and I've been able to reproduce locally... but this is not deterministic.  Launching the same command over and over finally get through locally. I'm not sure how to deal with this. Any idea?

**Comment by woshilapin** [comment]
I've reported an issue on `tarpaulin` project.
https://github.com/xd009642/tarpaulin/issues/461

**Comment by woshilapin** [comment]
I updated the PR and it seems to work fine.

**Comment by woshilapin** [comment]
This ticket adds a Github Action task to produce the Code Coverage and send it to CodeCov. This means we now have some visibility on code coverage. CodeCov will even produce a comment on each PR to show the evolution of coverage (see [Kirin repository](https://github.com/CanalTP/kirin/pull/317) for example).

**Review by pbougue — APPROVED** [review]
OK, we will also get a shield on top of readme.
And it should be quite easy to use codecov to spot where tests are missing.

**Pull request merged**
